version: '3.8'
services:
  ethglobal-backend-api:
    container_name: ethglobal-backend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
